### PR TITLE
Use first provider as default

### PR DESCRIPTION
**Pull request by EricHigdon**
See issue #19

### CODE REVIEW

**Comment by defionscode** [comment]
Looks like tests are failing, can you adjust tests appropriately?

**Comment by EricHigdon** [comment]
@defionscode Tests updated.

**Comment by defionscode** [comment]
@EricHigdon Looks good but I'm not sure you meant to include idea/vcs.xml? I think that's from pycharm no?

**Comment by EricHigdon** [comment]
@defionscode Ha. I'm dumb. Removed the .idea folder.

**Comment by defionscode** [comment]
It's now in pypi under `0.0.6`. Thanks for your work on this!

**Pull request merged**
